#ifndef REI_INTERNAL_SYMBOL_SYMBOL_H
#define REI_INTERNAL_SYMBOL_SYMBOL_H

typedef enum ReiSymbolKind
{
    REI_SYMBOL_KIND_GLOBAL,
    REI_SYMBOL_KIND_LOCAL,
    REI_SYMBOL_KIND_UPVALUE
} ReiSymbolKind;
typedef enum ReiSymbolScope
{
    REI_SYMBOL_SCOPE_GLOBAL,
    REI_SYMBOL_SCOPE_FUNCTION,
    REI_SYMBOL_SCOPE_CLASS
};

#endif
