#ifndef REI_LEXER_TOKEN_H
#define REI_LEXER_TOKEN_H

#include "../type/rei_value.h"

typedef enum ReiTokenKind
{
    REI_TOKEN_KIND_LEFT_PAREN,              // (
    REI_TOKEN_KIND_RIGHT_PAREN,             // )
    REI_TOKEN_KIND_LEFT_BRACKET,            // [
    REI_TOKEN_KIND_RIGHT_BRACKET,           // ]
    REI_TOKEN_KIND_LEFT_BRACE,              // {
    REI_TOKEN_KIND_RIGHT_BRACE,             // }

    REI_TOKEN_KIND_LEFT_BRACKET_BRACKET,    // [[
    REI_TOKEN_KIND_RIGHT_BRACKET_BRACKET,   // ]]

    REI_TOKEN_KIND_COMMA,       // ,
    REI_TOKEN_KIND_QUESTION,    // ?
    REI_TOKEN_KIND_DOT,         // .
    REI_TOKEN_KIND_DOT_DOT,     // ..
    REI_TOKEN_KIND_DOT_DOT_DOT, // ...
    REI_TOKEN_KIND_COLON,       // :
    REI_TOKEN_KIND_COLON_COLON,  // ::
    REI_TOKEN_KIND_SEMICOLON,   // ;
    
    REI_TOKEN_KIND_PLUS,        // +
    REI_TOKEN_KIND_MINUS,       // -
    REI_TOKEN_KIND_STAR,        // *
    REI_TOKEN_KIND_SLASH,       // /
    REI_TOKEN_KIND_MODULO,      // %
    REI_TOKEN_KIND_STAR_STAR,   // **

    REI_TOKEN_KIND_AND,             // &
    REI_TOKEN_KIND_PIPE,            // |
    REI_TOKEN_KIND_CTRL,            // ^
    REI_TOKEN_KIND_WAVE,            // ~
    REI_TOKEN_KIND_LESS_LESS,       // <<
    REI_TOKEN_KIND_GREATER_GREATER, // >>

    REI_TOKEN_KIND_AND_AND,         // &&
    REI_TOKEN_KIND_PIPE_PIPE,       // ||
    REI_TOKEN_KIND_BANG,            // !
    
    REI_TOKEN_KIND_LESS,                    // <
    REI_TOKEN_KIND_GREATER,                 // >
    REI_TOKEN_KIND_COMPARE,                 // <=>
    REI_TOKEN_KIND_EQUAL,                   // =
    REI_TOKEN_KIND_EQUAL_EQUAL,             // ==
    REI_TOKEN_KIND_BANG_EQUAL,              // !=
    REI_TOKEN_KIND_LESS_EQUAL,              // <=
    REI_TOKEN_KIND_GREATER_EQUAL,           // >=

    REI_TOKEN_KIND_COLON_EQUAL,             // :=

    REI_TOKEN_KIND_PLUS_EQUAL,              // +=
    REI_TOKEN_KIND_MINUS_EQUAL,             // -=
    REI_TOKEN_KIND_STAR_EQUAL,              // *=
    REI_TOKEN_KIND_SLASH_EQUAL,             // /=
    REI_TOKEN_KIND_MODULO_EQUAL,            // %=
    REI_TOKEN_KIND_STAR_STAR_EQUAL,         // **=
    REI_TOKEN_KIND_AND_EQUAL,               // &=
    REI_TOKEN_KIND_PIPE_EQUAL,              // |=
    REI_TOKEN_KIND_WAVE_EQUAL,              // ~=
    REI_TOKEN_KIND_LESS_LESS_EQUAL,         // <<=
    REI_TOKEN_KIND_GREATER_GREATER_EQUAL,   // >>=

    REI_TOKEN_KIND_LEFT_ARROW,  // <-
    REI_TOKEN_KIND_RIGHT_ARROW, // ->

    REI_TOKEN_KIND_POUND,   // \#
    REI_TOKEN_KIND_AT,      // @

    REI_TOKEN_KIND_NIL,     // NIL
    REI_TOKEN_KIND_TRUE,    // TRUE
    REI_TOKEN_KIND_FALSE,   // FALSE
    REI_TOKEN_KIND_INT,     // INT
    REI_TOKEN_KIND_FLOAT,   // FLOAT
    REI_TOKEN_KIND_STRING,  // STRING

    REI_TOKEN_KIND_IDENTIFIER,

    REI_TOKEN_KIND_MUT,
    REI_TOKEN_KIND_KON,

    REI_TOKEN_KIND_STATIC,

    REI_TOKEN_KIND_IF,
    REI_TOKEN_KIND_ELIF,
    REI_TOKEN_KIND_ELSE,

    REI_TOKEN_KIND_WHILE,
    REI_TOKEN_KIND_UNTIL,
    REI_TOKEN_KIND_CONTINUE,
    REI_TOKEN_KIND_BREAK,
    REI_TOKEN_KIND_DO,

    REI_TOKEN_KIND_SWITCH,
    REI_TOKEN_KIND_CASE,
    REI_TOKEN_KIND_PASS,
    REI_TOKEN_KIND_DEFAULT,

    REI_TOKEN_KIND_FUNC,
    REI_TOKEN_KIND_RETURN,
    
    REI_TOKEN_KIND_NAMESPACE,
    REI_TOKEN_KIND_EXTERNAL,
    REI_TOKEN_KIND_INTERNAL,

    REI_TOKEN_KIND_ENUM,
    REI_TOKEN_KIND_FLAG,
    REI_TOKEN_KIND_STRUCT,
    REI_TOKEN_KIND_CLASS,
    REI_TOKEN_KIND_INTERFACE,
    REI_TOKEN_KIND_TRAIT,
    REI_TOKEN_KIND_ATTRIBUTE,

    REI_TOKEN_KIND_PUBLIC,
    REI_TOKEN_KIND_PROTECTED,
    REI_TOKEN_KIND_PRIVATE,
    REI_TOKEN_KIND_SUPER,
    REI_TOKEN_KIND_THIS,
    REI_TOKEN_KIND_ABSTRACT,
    REI_TOKEN_KIND_SEALED,
    REI_TOKEN_KIND_FINAL,
    REI_TOKEN_KIND_VIRTUAL,
    REI_TOKEN_KIND_OVERRIDE,
    REI_TOKEN_KIND_UNDER_GET,
    REI_TOKEN_KIND_UNDER_SET,
    REI_TOKEN_KIND_NEW,
    REI_TOKEN_KIND_DEL,
    REI_TOKEN_KIND_IS,
    REI_TOKEN_KIND_HAS,

    REI_TOKEN_KIND_IMPORT,
    REI_TOKEN_KIND_AS,

    REI_TOKEN_KIND_RENAME,

    REI_TOKEN_KIND_DUNDER_MAIN,

    REI_TOKEN_KIND_DUNDER_INIT,
    REI_TOKEN_KIND_DUNDER_FREE,
    REI_TOKEN_KIND_DUNDER_ATIX,
    REI_TOKEN_KIND_DUNDER_CALL,
    REI_TOKEN_KIND_DUNDER_OPER,

    REI_TOKEN_KIND_EOF,

    REI_TOKEN_KIND_MAX_COUNT
} ReiTokenKind;
typedef struct ReiToken
{
    ReiTokenKind kind;
    struct
    {
    const char* start;
    int length;
    } lexeme;
    ReiValue literal;
    uint32_t line;
} ReiToken;

C_TEMPLATE_DECL_VECTOR(, rei, Rei, TokenBuffer, ReiToken)
C_TEMPLATE_DEFN_VECTOR(, rei, Rei, TokenBuffer, ReiToken)

#include "rei_token.debug.i"

#endif
