echo "-- expr --";
a := b := c := 1;
println "a, b, c = " + a + b + c;
a = 1; b = 2; c = 3;
println -a;
println ~a;
println !a;
println a + b;
println a - b;
println a * b;
println a / b;
println c % b;
println a ** b;
println a & b;
println a | b;
println a ^ b;
println a ` b;
println c << a;
println c >> a;
println a == b;
println a != b;
println a < b;
println a <= b;
println a > b;
println a >= b;
println a && b;
println a || b;
println -"abc";
println ~"def";
println !"ghi";
