#ifndef REI_PARSER_AST_H
#define REI_PARSER_AST_H

#include "../rei_internal.h"
#include REI_C_TEMPLATE_LIB_CONTAINER_VECTOR_H

typedef enum ReiAstNodeType
{
    REI_AST_NODE_TYPE_ROOT,
    REI_AST_NODE_TYPE_DECL_MUT,
    REI_AST_NODE_TYPE_DECL_KON,
    REI_AST_NODE_TYPE_DECL_ENUM,
    REI_AST_NODE_TYPE_DECL_FLAG,
    REI_AST_NODE_TYPE_DECL_FUNC,
    REI_AST_NODE_TYPE_DECL_CLASS,
    REI_AST_NODE_TYPE_EXPR_GROUP,
    REI_AST_NODE_TYPE_EXPR_LITERAL,
    REI_AST_NODE_TYPE_EXPR_IDENTIFIER,
    REI_AST_NODE_TYPE_EXPR_UNARY,
    REI_AST_NODE_TYPE_EXPR_BINARY,
    REI_AST_NODE_TYPE_EXPR_AND,
    REI_AST_NODE_TYPE_EXPR_OR,
    REI_AST_NODE_TYPE_EXPR_ATIX,
    REI_AST_NODE_TYPE_EXPR_CALL,
    REI_AST_NODE_TYPE_STMT_BLOCK,
    REI_AST_NODE_TYPE_STMT_IF,
    REI_AST_NODE_TYPE_STMT_WHILE,
    REI_AST_NODE_TYPE_STMT_BREAK,
    REI_AST_NODE_TYPE_STMT_CONTINUE,
    REI_AST_NODE_TYPE_STMT_SWITCH,
    REI_AST_NODE_TYPE_STMT_PASS,
    REI_AST_NODE_TYPE_STMT_RETURN,
    REI_AST_NODE_TYPE_STMT_NEW,
    REI_AST_NODE_TYPE_STMT_DEL,
    REI_AST_NODE_TYPE_STMT_IS,
    REI_AST_NODE_TYPE_MAX_COUNT
} ReiAstNodeType;
typedef enum ReiAstNodeCategory
{
    REI_AST_NODE_CATEGORY_ROOT,
    REI_AST_NODE_CATEGORY_DECL,
    REI_AST_NODE_CATEGORY_EXPR,
    REI_AST_NODE_CATEGORY_STMT,
    REI_AST_NODE_CATEGORY_MAX_COUNT
} ReiAstNodeCategory;
typedef struct ReiAst ReiAst, ReiAstNode;
typedef ReiAstNode* ReiAstNodePtr;
C_TEMPLATE_DECL_VECTOR(, rei, Rei, AstForest, ReiAstNodePtr)
C_TEMPLATE_DEFN_VECTOR(, rei, Rei, AstForest, ReiAstNodePtr)
struct ReiAst
{
    ReiAstNodeType type;
    ReiAstNodeCategory category;
    ReiAstNode* parent;
    ReiAstForest* children;
};

#endif
